### ISSUE TITLE
Incorrect Structure

### ISSUE THREAD

**Issue by amordahl** [WBales/3354-Ranged-Battle#2]
Good morning, Team Ranged Battle,

I wanted to make sure you take a second look at the project submission so you get the structure of your repository right. README.md should _only_ have your team name in it. The contents from the appendix go into a different file.

Let me know if you have any questions,

Austin

**Comment by WBales** [comment]
I added the project info thinking it would be useful. It is removed now. Do we also need to remove all information that is not the team name?

**Comment by amordahl** [comment]
The project info goes in the repository, just not in README.md. The specific instructions are in part two of the project 0 assignment.

On Sep 13, 2018 8:53 AM, WBales <notifications@github.com> wrote:

I added the project info thinking it would be useful. It is removed now. Do we also need to remove all information that is not the team name?
